version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '07:00'
    open-pull-requests-limit: 0 # soft disable for `renovate` migration test
